pullInterval: 5

clusters:
  myproject1:
    groups:
      common:
        agent: "pull"
        path: "/"
        secure: false
        port: 9999
        hosts: 
          - "127.0.0.1"
  myproject2:
    groups:
      web:
        agent: "pull"
        path: "/"
        secure: false
        port: 9999
        hosts: 
          - "127.0.0.1"
      cron:
        agent: "push"
        hosts: 
          - "127.0.0.1"

ui:
  host: 127.0.0.1
  port: 42042

metrics:
  statsd:
    enabled: false
    host: 127.0.0.1
    port: 8125
    prefix: some.metric.prefix
  prometheus:
    enabled: false
    