pullInterval: 5

clusters:
  myproject1:
    groups:
      common:
        urlPattern: "{schema}://127.0.0.1:{port}/{host}{path}"
        agent: "pull"
        path: "/agent-pull.php"
        secure: false
        basicAuth:
          user: someuser
          password: somepassword
        port: 9999
        hosts: 
          - "some-host-name"
          - "some-other-host-name"
  myproject2:
    groups:
      web:
        agent: "pull"
        path: "/"
        secure: false
        port: 9999
        hosts: 
          - "127.0.0.1"
      cron:
        agent: "push"
        hosts: 
          - "127.0.0.1"

ui:
  host: 127.0.0.1
  port: 42042

metrics:
  statsd:
    enabled: false
    host: 127.0.0.1
    port: 8125
    prefix: some.metric.prefix
  prometheus:
    enabled: true
    
